### ISSUE TITLE
Undefined array key "class" in ServiceMap

### ISSUE THREAD

**Issue by mondrake** [mglaman/phpstan-drupal#222] opened 2021-11-10 17:02 UTC
Hi, I am getting the message below when trying to run PHPStan on Drupal core, out there at https://www.drupal.org/project/drupal/issues/3178534.

```
17:55:49 cd ${SOURCE_DIR}/core && sudo -u www-data ../vendor/bin/phpstan analyze
17:55:50 Note: Using configuration file /var/www/html/core/phpstan.neon.dist.
17:55:51 PHP Warning:  Undefined array key "class" in /var/www/html/vendor/mglaman/phpstan-drupal/src/Drupal/ServiceMap.php on line 41
17:55:51 Warning: Undefined array key "class" in /var/www/html/vendor/mglaman/phpstan-drupal/src/Drupal/ServiceMap.php on line 41
```

Looking at the code,

```

            if (!isset($serviceDefinition['class'])) {
                if (isset($serviceDefinition['alias'], $drupalServices[$serviceDefinition['alias']])) {
                    $serviceDefinition['class'] = $drupalServices[$serviceDefinition['alias']]['class'];
                } else {
                    continue;
                }
            }
```

seems a legit bug when `$drupalServices[$serviceDefinition['alias']]` is missing the 'class' key, there is no earlier check about that case.

**Comment by longwave** [comment] 2021-11-10 21:08
Duplicate of #184 :)

**Comment by mondrake** [comment] 2021-11-10 21:12
> Duplicate of #184 :)

I should have checked ...

**Closed** 2021-11-10 21:46 UTC

**Comment by mglaman** [comment] 2021-11-10 22:10
I missed it too 😅. But at least its fixed!
